name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} + Rails ${{ matrix.rails }}
    strategy:
      matrix:
        rails:
          - '7.0'
          - '7.1'
          - '7.2'
          - '8'
          - 'main'
        ruby:
          - '3.4'
          - '3.3'
          - '3.2'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run all tests
      run: |
        bundle exec rake --trace
